### ISSUE TITLE
Documentation on usage of DefaultVersions plugin

### ISSUE THREAD

**Issue by samtuke** [spmeesseman/mantisbt-plugins#1]
Please add information to the README regarding how to use the DefaultVersions plugin, such as where the default version is set, and any caveats such as how it is applied to different projects etc.

**Comment by samtuke** [comment]
I have installed the plugin but do not see new files or options on the 'manage projects' page.

**Comment by samtuke** [comment]
Any additional documentation would be useful ...

**Comment by spmeesseman** [comment]
coming soon....

**Comment by spmeesseman** [comment]
I updated the documentation, the only "UI" you'll see is the config page (Manage -> Plugins -> Default Versions)... you wont find anything in manage projects.
